run:
  timeout: 30m

output:
  sort-results: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  disable-all: true
  enable: # please keep this alphabetized
    - logcheck

linters-settings: # please keep this alphabetized
  custom:
    logcheck:
      # Installed there by Makefile.
      path: hack/tools/bin/logcheck.so
      description: structured logging checker
      original-url: k8s.io/logtools/logcheck
